name: Pull Request build+deploy

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Starting deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: integration
          ref: ${{ github.head_ref }}

      - name: Checkout code
        uses: actions/checkout@v2

      # Cache node modules and next folder
      - name: 📬 Caching
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          envkey_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          envkey_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          envkey_FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          envkey_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          envkey_FIREBASE_SENDER_ID: ${{ secrets.FIREBASE_SENDER_ID }}
          envkey_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          envkey_AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          envkey_AUTH0_BASE_URL: ${{ secrets.AUTH0_BASE_URL }}
          envkey_AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
          envkey_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          envkey_AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          envkey_NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          file_name: '.env'

      - name: Add Firebase secret
        run: |
          mkdir secrets
          echo $FIREBASE_ADMIN_CREDENTIALS | base64 -d > secrets/firebase_admin_credentials.json
        env:
          FIREBASE_ADMIN_CREDENTIALS: ${{ secrets.FIREBASE_ADMIN_CREDENTIALS }}

      - name: 🧰 Install dependencies
        run: |
          npm install -g yarn
          yarn install

      # - name: 🧹 Run lint
      #   run: npm run lint

      - name: 🐛 Run tests
        run: yarn test

      - name: 🛠   Bild project
        id: build-netlify
        run: |
          netlify build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: 🌍 Preview deploy to Netlify
        id: preview-deploy
        run: |
          COMMAND="netlify deploy -m \'${{ github.head_ref }}\' --alias \'${{ github.head_ref }}\'"
          OUTPUT=$(sh -c "$COMMAND")
          NETLIFY_URL=$(echo "$OUTPUT" | grep -Eo '(http|https)://[a-zA-Z0-9./?=_-]*(--)[a-zA-Z0-9./?=_-]*') #Unique key: --
          NETLIFY_LOGS_URL=$(echo "$OUTPUT" | grep -Eo '(http|https)://app.netlify.com/[a-zA-Z0-9./?=_-]*') #Unique key: app.netlify.com

          echo "::set-output name=NETLIFY_OUTPUT::$OUTPUT"
          echo "::set-output name=NETLIFY_URL::$NETLIFY_URL"
          echo "::set-output name=NETLIFY_LOGS_URL::$NETLIFY_LOGS_URL"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ steps.preview-deploy.outputs.NETLIFY_URL }}
          logs: ${{ steps.preview-deploy.outputs.NETLIFY_LOGS_URL }}
